/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, nullable, object, optional, Schema, string } from '../schema';

/** This custom type contains response for definitions endpoint. */
export interface DefinitionsResponse {
  /** The word that is searched. */
  word?: string | null;
  /** The definitions of the searched word. */
  definition?: string[] | null;
}

export const definitionsResponseSchema: Schema<DefinitionsResponse> = object({
  word: ['word', optional(nullable(string()))],
  definition: ['definition', optional(nullable(array(string())))],
});
