/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** This custom type contains response for definitions endpoint. */
export interface DefinitionsResponse {
  /** The word that is searched. */
  word: string;
  /** The definitions of the searched word. */
  definition: string[];
}

export const definitionsResponseSchema: Schema<DefinitionsResponse> = object({
  word: ['word', string()],
  definition: ['definition', array(string())],
});
