/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, nullable, object, optional, Schema, string } from '../schema';

/** This custom type contains response for examples endpoint. */
export interface ExamplesResponse {
  /** The word that is searched. */
  word?: string | null;
  /** The usage examples of the searched word. */
  examples?: string[] | null;
}

export const examplesResponseSchema: Schema<ExamplesResponse> = object({
  word: ['word', optional(nullable(string()))],
  examples: ['examples', optional(nullable(array(string())))],
});
