/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** This custom type contains response for examples endpoint. */
export interface ExamplesResponse {
  /** The word that is searched. */
  word: string;
  /** The usage examples of the searched word. */
  examples: string[];
}

export const examplesResponseSchema: Schema<ExamplesResponse> = object({
  word: ['word', string()],
  examples: ['examples', array(string())],
});
