/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema';
import { FrequencyDetails, frequencyDetailsSchema } from './frequencyDetails';

/** This custom type contains response for frequency endpoint. */
export interface FrequencyResponse {
  /** The word that is searched. */
  word?: string | null;
  /** This model contains frequency details of a specific word. */
  frequency?: FrequencyDetails | null;
}

export const frequencyResponseSchema: Schema<FrequencyResponse> = object({
  word: ['word', optional(nullable(string()))],
  frequency: [
    'frequency',
    optional(nullable(lazy(() => frequencyDetailsSchema))),
  ],
});
