/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema } from '../schema';

/** This model contains frequency details of a specific word. */
export interface FrequencyDetails {
  /** Explains the zipf score. */
  zipf?: number | null;
  /** Explains the perMillion score. */
  perMillion?: number | null;
  /** Explains the diversity score. */
  diversity?: number | null;
}

export const frequencyDetailsSchema: Schema<FrequencyDetails> = object({
  zipf: ['zipf', optional(nullable(number()))],
  perMillion: ['perMillion', optional(nullable(number()))],
  diversity: ['diversity', optional(nullable(number()))],
});
