/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

/** This custom type contains the syllable details for word API. */
export interface SyllableDetails {
  /** The count of syllables. */
  count?: number;
  /** The list of syllables. */
  list?: string[];
}

export const syllableDetailsSchema: Schema<SyllableDetails> = object({
  count: ['count', optional(number())],
  list: ['list', optional(array(string()))],
});
