/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

/** This custom type contains the syllable details for word API. */
export interface SyllableDetails {
  /** The count of syllables. */
  count?: number | null;
  /** The list of syllables. */
  list?: string[] | null;
}

export const syllableDetailsSchema: Schema<SyllableDetails> = object({
  count: ['count', optional(nullable(number()))],
  list: ['list', optional(nullable(array(string())))],
});
