/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** This custom type contains response for synonyms endpoint. */
export interface SynonymsResponse {
  /** The word that is searched. */
  word: string;
  /** The synonyms of the searched word. */
  synonyms: string[];
}

export const synonymsResponseSchema: Schema<SynonymsResponse> = object({
  word: ['word', string()],
  synonyms: ['synonyms', array(string())],
});
