/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

/** This custom type stores word information. */
export interface WordDetails {
  /** Explains the definition of the word. */
  definition?: string;
  /** Explains what part of speech the word is. */
  partOfSpeech?: string;
  /** The list of synonyms. */
  synonyms?: string[];
  /** List of words that are more general than the searched word. */
  typeOf?: string[];
  /** More specific examples of types of searched word. */
  hasTypes?: string[];
  /** The derivation if any. */
  derivation?: string[];
  /** The usage examples of word if any. */
  examples?: string[];
  /** List of antonyms for the searched word. */
  antonyms?: string[];
  /** The verb group of the searched word. */
  verbGroup?: string[];
  /** Words that are parts of the searched word. */
  hasParts?: string[];
  /** Words that are substances of the searched word. */
  hasSubstances?: string[];
  /** Words that are implied by the searched word. Usually used for verbs. */
  entails?: string[];
}

export const wordDetailsSchema: Schema<WordDetails> = object({
  definition: ['definition', optional(string())],
  partOfSpeech: ['partOfSpeech', optional(string())],
  synonyms: ['synonyms', optional(array(string()))],
  typeOf: ['typeOf', optional(array(string()))],
  hasTypes: ['hasTypes', optional(array(string()))],
  derivation: ['derivation', optional(array(string()))],
  examples: ['examples', optional(array(string()))],
  antonyms: ['antonyms', optional(array(string()))],
  verbGroup: ['verbGroup', optional(array(string()))],
  hasParts: ['hasParts', optional(array(string()))],
  hasSubstances: ['hasSubstances', optional(array(string()))],
  entails: ['entails', optional(array(string()))],
});
