/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { SyllableDetails, syllableDetailsSchema } from './syllableDetails';
import { WordDetails, wordDetailsSchema } from './wordDetails';

/** This custom type contains the response for word API. */
export interface WordResponse {
  /** The word that is searched. */
  word?: string | null;
  /** This field contains detailed information of the word. */
  results?: WordDetails[] | null;
  /** This model contains pronunciation details of a specific word. */
  pronunciation?: unknown | null;
  /** The frequency of the word usage. */
  frequency?: number | null;
  /** This custom type contains the syllable details for word API. */
  syllables?: SyllableDetails | null;
}

export const wordResponseSchema: Schema<WordResponse> = object({
  word: ['word', optional(nullable(string()))],
  results: [
    'results',
    optional(nullable(array(lazy(() => wordDetailsSchema)))),
  ],
  pronunciation: ['pronunciation', optional(nullable(unknown()))],
  frequency: ['frequency', optional(nullable(number()))],
  syllables: [
    'syllables',
    optional(nullable(lazy(() => syllableDetailsSchema))),
  ],
});
