/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { SyllableDetails, syllableDetailsSchema } from './syllableDetails';
import { WordDetails, wordDetailsSchema } from './wordDetails';

/** This custom type contains the response for word API. */
export interface WordResponse {
  /** The word that is searched. */
  word: string;
  /** This field contains detailed information of the word. */
  results: WordDetails[];
  /** This model contains pronunciation details of a specific word. */
  pronunciation?: unknown;
  /** The frequency of the word usage. */
  frequency?: number;
  /** This custom type contains the syllable details for word API. */
  syllables?: SyllableDetails;
}

export const wordResponseSchema: Schema<WordResponse> = object({
  word: ['word', string()],
  results: ['results', array(lazy(() => wordDetailsSchema))],
  pronunciation: ['pronunciation', optional(unknown())],
  frequency: ['frequency', optional(number())],
  syllables: ['syllables', optional(lazy(() => syllableDetailsSchema))],
});
