/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, nullable, object, optional, Schema, string } from '../schema';

/** This custom type stores word information. */
export interface WordDetails {
  /** Explains the definition of the word. */
  definition?: string | null;
  /** Explains what part of speech the word is. */
  partOfSpeech?: string | null;
  /** The list of synonyms. */
  synonyms?: string[] | null;
  /** List of words that are more general than the searched word. */
  typeOf?: string[] | null;
  /** More specific examples of types of searched word. */
  hasTypes?: string[] | null;
  /** The derivation if any. */
  derivation?: string[] | null;
  /** The usage examples of word if any. */
  examples?: string[] | null;
  /** List of antonyms for the searched word. */
  antonyms?: string[] | null;
  /** The verb group of the searched word. */
  verbGroup?: string[] | null;
  /** Words that are parts of the searched word. */
  hasParts?: string[] | null;
  /** Words that are substances of the searched word. */
  hasSubstances?: string[] | null;
  /** Words that are implied by the searched word. Usually used for verbs. */
  entails?: string[] | null;
}

export const wordDetailsSchema: Schema<WordDetails> = object({
  definition: ['definition', optional(nullable(string()))],
  partOfSpeech: ['partOfSpeech', optional(nullable(string()))],
  synonyms: ['synonyms', optional(nullable(array(string())))],
  typeOf: ['typeOf', optional(nullable(array(string())))],
  hasTypes: ['hasTypes', optional(nullable(array(string())))],
  derivation: ['derivation', optional(nullable(array(string())))],
  examples: ['examples', optional(nullable(array(string())))],
  antonyms: ['antonyms', optional(nullable(array(string())))],
  verbGroup: ['verbGroup', optional(nullable(array(string())))],
  hasParts: ['hasParts', optional(nullable(array(string())))],
  hasSubstances: ['hasSubstances', optional(nullable(array(string())))],
  entails: ['entails', optional(nullable(array(string())))],
});
