/**
 * Words APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

export * from './client';
export * from './configuration';
export {
  AbortError,
  ApiResponse,
  ArgumentsValidationError,
  cloneFileWrapper,
  FileWrapper,
  isFileWrapper,
  ResponseValidationError,
} from './core';
export * from './defaultConfiguration';
export * from './controllers/aPIsController';
export { ApiError } from './core';
export { DefinitionsResponse } from './models/definitionsResponse';
export { ExamplesResponse } from './models/examplesResponse';
export { FrequencyDetails } from './models/frequencyDetails';
export { FrequencyResponse } from './models/frequencyResponse';
export { PronunciationDetails } from './models/pronunciationDetails';
export { PronunciationResponse } from './models/pronunciationResponse';
export { SyllableDetails } from './models/syllableDetails';
export { SynonymsResponse } from './models/synonymsResponse';
export { WordDetails } from './models/wordDetails';
export { WordResponse } from './models/wordResponse';
